from typing import Callable, List, Optional


class Options:
    def help(self) -> str: ...
    def has_value(self, lkey: str) -> bool: ...
    def flag(self, lkey: str) -> bool: ...
    def number(self, lkey: str) -> int: ...
    def param(self, lkey: str) -> Optional[str]: ...
    def params(self, lkey: str) -> List[str]: ...


class Node:
    def flag(self, lkey: str, skey: Optional[str] = ..., msg: str = ...) -> None: ...
    def number(
        self,
        lkey: str,
        skey: Optional[str] = ...,
        msg: str = ...,
        fallback: Optional[int] = ...,
        implicit: Optional[int] = ...,
    ) -> None: ...
    def param(self, lkey: str, skey: Optional[str] = ..., msg: str = ..., fallback: Optional[str] = ...) -> None: ...
    def params(self, lkey: str, skey: Optional[str] = ..., msg: str = ...) -> None: ...
    def use(self, fn: Callable[[Options], Optional[int]]) -> None: ...
    def sub(self, key: str, description: str, fn: Callable[["Node"], None]) -> None: ...
    def run(self, argv: List[str]) -> int: ...
    def destroy(self) -> None: ...


class Clix:
    def __init__(self, clix: object) -> None: ...
    def create_node(self) -> Node: ...


def create_node() -> Node: ...


__all__: List[str]
