#!/usr/bin/env bash

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

export CC=`(which clang-18)`
export CXX=`(which clang++-18)`
export TRIPLET="-DVCPKG_TARGET_TRIPLET=nil-libcxx -DVCPKG_HOST_TRIPLET=nil-libcxx"

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
REPO_PATH=`(realpath $SCRIPT_PATH/..)`
cd $REPO_PATH

configure/command $@